require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MoldSparesController do

  # This should return the minimal set of attributes required to create a valid
  # MoldSpare. As you add validations to MoldSpare, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MoldSparesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mold_spares as @mold_spares" do
      mold_spare = MoldSpare.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mold_spares).should eq([mold_spare])
    end
  end

  describe "GET show" do
    it "assigns the requested mold_spare as @mold_spare" do
      mold_spare = MoldSpare.create! valid_attributes
      get :show, {:id => mold_spare.to_param}, valid_session
      assigns(:mold_spare).should eq(mold_spare)
    end
  end

  describe "GET new" do
    it "assigns a new mold_spare as @mold_spare" do
      get :new, {}, valid_session
      assigns(:mold_spare).should be_a_new(MoldSpare)
    end
  end

  describe "GET edit" do
    it "assigns the requested mold_spare as @mold_spare" do
      mold_spare = MoldSpare.create! valid_attributes
      get :edit, {:id => mold_spare.to_param}, valid_session
      assigns(:mold_spare).should eq(mold_spare)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MoldSpare" do
        expect {
          post :create, {:mold_spare => valid_attributes}, valid_session
        }.to change(MoldSpare, :count).by(1)
      end

      it "assigns a newly created mold_spare as @mold_spare" do
        post :create, {:mold_spare => valid_attributes}, valid_session
        assigns(:mold_spare).should be_a(MoldSpare)
        assigns(:mold_spare).should be_persisted
      end

      it "redirects to the created mold_spare" do
        post :create, {:mold_spare => valid_attributes}, valid_session
        response.should redirect_to(MoldSpare.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mold_spare as @mold_spare" do
        # Trigger the behavior that occurs when invalid params are submitted
        MoldSpare.any_instance.stub(:save).and_return(false)
        post :create, {:mold_spare => { "name" => "invalid value" }}, valid_session
        assigns(:mold_spare).should be_a_new(MoldSpare)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MoldSpare.any_instance.stub(:save).and_return(false)
        post :create, {:mold_spare => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mold_spare" do
        mold_spare = MoldSpare.create! valid_attributes
        # Assuming there are no other mold_spares in the database, this
        # specifies that the MoldSpare created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MoldSpare.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => mold_spare.to_param, :mold_spare => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested mold_spare as @mold_spare" do
        mold_spare = MoldSpare.create! valid_attributes
        put :update, {:id => mold_spare.to_param, :mold_spare => valid_attributes}, valid_session
        assigns(:mold_spare).should eq(mold_spare)
      end

      it "redirects to the mold_spare" do
        mold_spare = MoldSpare.create! valid_attributes
        put :update, {:id => mold_spare.to_param, :mold_spare => valid_attributes}, valid_session
        response.should redirect_to(mold_spare)
      end
    end

    describe "with invalid params" do
      it "assigns the mold_spare as @mold_spare" do
        mold_spare = MoldSpare.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MoldSpare.any_instance.stub(:save).and_return(false)
        put :update, {:id => mold_spare.to_param, :mold_spare => { "name" => "invalid value" }}, valid_session
        assigns(:mold_spare).should eq(mold_spare)
      end

      it "re-renders the 'edit' template" do
        mold_spare = MoldSpare.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MoldSpare.any_instance.stub(:save).and_return(false)
        put :update, {:id => mold_spare.to_param, :mold_spare => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mold_spare" do
      mold_spare = MoldSpare.create! valid_attributes
      expect {
        delete :destroy, {:id => mold_spare.to_param}, valid_session
      }.to change(MoldSpare, :count).by(-1)
    end

    it "redirects to the mold_spares list" do
      mold_spare = MoldSpare.create! valid_attributes
      delete :destroy, {:id => mold_spare.to_param}, valid_session
      response.should redirect_to(mold_spares_url)
    end
  end

end
