require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SubsectionsController do

  # This should return the minimal set of attributes required to create a valid
  # Subsection. As you add validations to Subsection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "code" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SubsectionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all subsections as @subsections" do
      subsection = Subsection.create! valid_attributes
      get :index, {}, valid_session
      assigns(:subsections).should eq([subsection])
    end
  end

  describe "GET show" do
    it "assigns the requested subsection as @subsection" do
      subsection = Subsection.create! valid_attributes
      get :show, {:id => subsection.to_param}, valid_session
      assigns(:subsection).should eq(subsection)
    end
  end

  describe "GET new" do
    it "assigns a new subsection as @subsection" do
      get :new, {}, valid_session
      assigns(:subsection).should be_a_new(Subsection)
    end
  end

  describe "GET edit" do
    it "assigns the requested subsection as @subsection" do
      subsection = Subsection.create! valid_attributes
      get :edit, {:id => subsection.to_param}, valid_session
      assigns(:subsection).should eq(subsection)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Subsection" do
        expect {
          post :create, {:subsection => valid_attributes}, valid_session
        }.to change(Subsection, :count).by(1)
      end

      it "assigns a newly created subsection as @subsection" do
        post :create, {:subsection => valid_attributes}, valid_session
        assigns(:subsection).should be_a(Subsection)
        assigns(:subsection).should be_persisted
      end

      it "redirects to the created subsection" do
        post :create, {:subsection => valid_attributes}, valid_session
        response.should redirect_to(Subsection.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved subsection as @subsection" do
        # Trigger the behavior that occurs when invalid params are submitted
        Subsection.any_instance.stub(:save).and_return(false)
        post :create, {:subsection => { "code" => "invalid value" }}, valid_session
        assigns(:subsection).should be_a_new(Subsection)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Subsection.any_instance.stub(:save).and_return(false)
        post :create, {:subsection => { "code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested subsection" do
        subsection = Subsection.create! valid_attributes
        # Assuming there are no other subsections in the database, this
        # specifies that the Subsection created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Subsection.any_instance.should_receive(:update).with({ "code" => "MyString" })
        put :update, {:id => subsection.to_param, :subsection => { "code" => "MyString" }}, valid_session
      end

      it "assigns the requested subsection as @subsection" do
        subsection = Subsection.create! valid_attributes
        put :update, {:id => subsection.to_param, :subsection => valid_attributes}, valid_session
        assigns(:subsection).should eq(subsection)
      end

      it "redirects to the subsection" do
        subsection = Subsection.create! valid_attributes
        put :update, {:id => subsection.to_param, :subsection => valid_attributes}, valid_session
        response.should redirect_to(subsection)
      end
    end

    describe "with invalid params" do
      it "assigns the subsection as @subsection" do
        subsection = Subsection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Subsection.any_instance.stub(:save).and_return(false)
        put :update, {:id => subsection.to_param, :subsection => { "code" => "invalid value" }}, valid_session
        assigns(:subsection).should eq(subsection)
      end

      it "re-renders the 'edit' template" do
        subsection = Subsection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Subsection.any_instance.stub(:save).and_return(false)
        put :update, {:id => subsection.to_param, :subsection => { "code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested subsection" do
      subsection = Subsection.create! valid_attributes
      expect {
        delete :destroy, {:id => subsection.to_param}, valid_session
      }.to change(Subsection, :count).by(-1)
    end

    it "redirects to the subsections list" do
      subsection = Subsection.create! valid_attributes
      delete :destroy, {:id => subsection.to_param}, valid_session
      response.should redirect_to(subsections_url)
    end
  end

end
