require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ZombiesController do

  # This should return the minimal set of attributes required to create a valid
  # Zombie. As you add validations to Zombie, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ZombiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all zombies as @zombies" do
      zombie = Zombie.create! valid_attributes
      get :index, {}, valid_session
      assigns(:zombies).should eq([zombie])
    end
  end

  describe "GET show" do
    it "assigns the requested zombie as @zombie" do
      zombie = Zombie.create! valid_attributes
      get :show, {:id => zombie.to_param}, valid_session
      assigns(:zombie).should eq(zombie)
    end
  end

  describe "GET new" do
    it "assigns a new zombie as @zombie" do
      get :new, {}, valid_session
      assigns(:zombie).should be_a_new(Zombie)
    end
  end

  describe "GET edit" do
    it "assigns the requested zombie as @zombie" do
      zombie = Zombie.create! valid_attributes
      get :edit, {:id => zombie.to_param}, valid_session
      assigns(:zombie).should eq(zombie)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Zombie" do
        expect {
          post :create, {:zombie => valid_attributes}, valid_session
        }.to change(Zombie, :count).by(1)
      end

      it "assigns a newly created zombie as @zombie" do
        post :create, {:zombie => valid_attributes}, valid_session
        assigns(:zombie).should be_a(Zombie)
        assigns(:zombie).should be_persisted
      end

      it "redirects to the created zombie" do
        post :create, {:zombie => valid_attributes}, valid_session
        response.should redirect_to(Zombie.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved zombie as @zombie" do
        # Trigger the behavior that occurs when invalid params are submitted
        Zombie.any_instance.stub(:save).and_return(false)
        post :create, {:zombie => {  }}, valid_session
        assigns(:zombie).should be_a_new(Zombie)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Zombie.any_instance.stub(:save).and_return(false)
        post :create, {:zombie => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested zombie" do
        zombie = Zombie.create! valid_attributes
        # Assuming there are no other zombies in the database, this
        # specifies that the Zombie created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Zombie.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => zombie.to_param, :zombie => { "these" => "params" }}, valid_session
      end

      it "assigns the requested zombie as @zombie" do
        zombie = Zombie.create! valid_attributes
        put :update, {:id => zombie.to_param, :zombie => valid_attributes}, valid_session
        assigns(:zombie).should eq(zombie)
      end

      it "redirects to the zombie" do
        zombie = Zombie.create! valid_attributes
        put :update, {:id => zombie.to_param, :zombie => valid_attributes}, valid_session
        response.should redirect_to(zombie)
      end
    end

    describe "with invalid params" do
      it "assigns the zombie as @zombie" do
        zombie = Zombie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Zombie.any_instance.stub(:save).and_return(false)
        put :update, {:id => zombie.to_param, :zombie => {  }}, valid_session
        assigns(:zombie).should eq(zombie)
      end

      it "re-renders the 'edit' template" do
        zombie = Zombie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Zombie.any_instance.stub(:save).and_return(false)
        put :update, {:id => zombie.to_param, :zombie => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested zombie" do
      zombie = Zombie.create! valid_attributes
      expect {
        delete :destroy, {:id => zombie.to_param}, valid_session
      }.to change(Zombie, :count).by(-1)
    end

    it "redirects to the zombies list" do
      zombie = Zombie.create! valid_attributes
      delete :destroy, {:id => zombie.to_param}, valid_session
      response.should redirect_to(zombies_url)
    end
  end

end
